name: Build and do smoke test on Push or Pull request

on:
  #push:
  #  branches:
  # - main
  pull_request:
    branches:
    - main
    
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-12, windows-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
      - uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ matrix.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      #- uses: gradle/gradle-build-action@v2
      #- run: ./gradlew smokeTest
      #  working-directory: org.jtool.jxplatform