name: Assmeble, Do smoke test, and Publish javadoc on Push or Pull request

on:
  push:
    branches:
    - main
    paths:
      - 'org.jtool.jxplatform/**'
  pull_request:
    branches:
    - main
    paths:
      - 'org.jtool.jxplatform/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout from Git
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
          cache: 'gradle'

      - name: Assemble
        run: ./gradlew assemble
        working-directory: org.jtool.jxplatform

      - name: Do smoke test
        run: ./gradlew smokeTest
        working-directory: org.jtool.jxplatform

  publish:
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout from Git
        uses: actions/checkout@v3

      - name: Setup pages
        uses: actions/configure-pages@v2

      - name: Generate javadoc
        run: ./gradlew javadoc
        working-directory: org.jtool.jxplatform

      - name: Upload javadoc
        uses: actions/upload-pages-artifact@v1
        with:
          path: org.jtool.jxplatform/build/docs/javadoc/

      - name: Deploy javadoc to GitHub pages
        id: deployment
        uses: actions/deploy-pages@v1
