name: Build and run unit-test on Push or Pull request

on:
  push:
    branches:
    - main
  # tags:
  # - 'v**'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
      - uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ matrix.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - uses: gradle/gradle-build-action@v2
      - run: ./gradlew jar
        working-directory: org.jtool.jxplatform
      - run: ./gradlew shadowJar
        working-directory: org.jtool.jxplatform
        
  release:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - run:
          mkdir -p ./org.jtool.jxplatform/releases
          cp ./org.jtool.jxplatform/build/libs/* ./org.jtool.jxplatform/releases
      - uses: gradle/gradle-build-action@v2
      - run: ./gradlew javadoc
        working-directory: org.jtool.jxplatform
      - uses: actions/upload-artifact@v3
        with:
          name: latest-releases
          path: ./org.jtool.jxplatform/releases
      - id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      - id: get_commit_summary
        run: |
          PREVIOUS_TAG=$(git tag --sort=-creatordate | sed -n 2p)
          echo "PREVIOUS_TAG: $PREVIOUS_TAG"
          COMMIT_SUMMARY="$(git log --oneline --pretty=tformat:"%h %s" $PREVIOUS_TAG..${{ github.ref }})"
          COMMIT_SUMMARY="${COMMIT_SUMMARY//$'\n'/'%0A'}"
          echo "COMMIT_SUMMARY=$COMMIT_SUMMARY" >> $GITHUB_OUTPUT
      - id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.VERSION }}
          release_name: Version ${{ steps.get_version.outputs.VERSION }}
          body: |
            ${{ steps.get_commit_summary.outputs.COMMIT_SUMMARY }}
          draft: false
          prerelease: false
